name: v14-image-publish

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: v14
    
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: log into docker registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: publish docker image
        uses: docker/build-push-action@v2
        if: steps.checkImage.outputs.code != 200
        with:
          context: v14
          platforms: linux/amd64,linux/arm64
          file: ./v14/Dockerfile
          push: true
          tags: |
            docker.io/sarumont/postgres-plus:latest
            docker.io/sarumont/postgres-plus:v14
